# The validation evidence (vignettes/tte-validation-evidence.rds) records the
# swereg version that generated it in `$meta$swereg`. This test is always on:
# a release whose DESCRIPTION version differs from that field ships evidence
# from another version. The estimator-source check is in the full tier
# (test-validation-full.R), because it reads R/ files.

test_that("the validation evidence was generated by the DESCRIPTION version", {
  root <- val_package_root()
  expect_false(is.null(root), label = "a package root holding DESCRIPTION")
  path <- file.path(root, "vignettes", "tte-validation-evidence.rds")
  expect_true(file.exists(path), label = path)
  ev <- readRDS(path)
  version <- unname(read.dcf(file.path(root, "DESCRIPTION"))[1L, "Version"])
  expect_identical(ev$meta$swereg, version)
})
