# Applying one code registry entry to a skeleton, and predicting the columns it writes.

# Predict the character vector of column names that a single code within a
# registry entry will contribute to a skeleton. Mirrors the prefixing logic
# inside .apply_code_entry_impl() below.
#
# Primary entries: for each (group_prefix, code_name) pair in
# (groups x code_name), the column is `prefix_code_name` (or just
# `code_name` when the prefix is empty). When `combine_as` is set, one
# additional column is produced with `combine_as_code_name`.
#
# Derived entries (kind = "derived"): one column per code_name of the form
# `<as>_<code_name>`, built by OR-ing `<from[i]>_<code_name>` across the
# upstream source prefixes. No group machinery.
#
# This is the single source of truth for column-name prediction. It is
# used by:
#   - RegistryStudy$summary_table() (via .entry_columns())
#   - Skeleton$drop_code_entry() via .entry_columns() on stored descriptors,
#     to know which columns to remove when a registry entry is dropped
.generated_columns_for_entry <- function(reg, code_name) {
  kind <- reg$kind %||% "primary"
  if (identical(kind, "derived")) {
    return(paste0(reg$as, "_", code_name))
  }
  cols <- character()
  for (i in seq_along(reg$groups)) {
    prefix <- names(reg$groups)[i]
    if (!is.null(prefix) && nzchar(prefix)) {
      cols <- c(cols, paste0(prefix, "_", code_name))
    } else {
      cols <- c(cols, code_name)
    }
  }
  if (!is.null(reg$combine_as)) {
    cols <- c(cols, paste0(reg$combine_as, "_", code_name))
  }
  return(cols)
}

# Vectorized wrapper: predict the full character vector of column names a
# registry entry contributes, across ALL its code names. Used by the
# Skeleton R6 class at drop time. The prediction MUST stay in sync with
# the behavior of every built-in `fn` (add_diagnoses, add_rx, add_operations,
# add_cancer_without_morphology, add_quality_registry); the parity tests in
# tests/testthat/test-entry_columns_parity.R enforce this invariant.
.entry_columns <- function(reg) {
  return(unlist(
    lapply(
      names(reg$codes),
      function(code_name) .generated_columns_for_entry(reg, code_name)
    ),
    use.names = FALSE
  ) %||%
    character())
}

# Two rules an entry MUST satisfy before it joins the registry.
#
# 1. Every group it names is in the study's `group_names`.
#    `$load_rawbatch()` reads one file per name in `group_names`, so a name
#    outside that set never arrives. Without this check the run starts, and
#    phase 2 stops part way through it.
# 2. No column it generates is already generated by a registered entry.
#    `$drop_code_entry()` removes exactly the columns an entry declares, so
#    two owners of one column make a drop of either one delete the other's
#    output. Replay then rewrites only the entry whose fingerprint moved, and
#    the surviving value is the wrong writer's.
#
# A real study's registry was checked against both rules before this check
# shipped, and satisfied them.
.assert_entry_registrable <- function(entry, registry, group_names) {
  context <- .entry_context(entry)
  if (!identical(entry$kind %||% "primary", "derived")) {
    unknown <- setdiff(unique(unlist(entry$groups)), group_names)
    if (length(unknown) > 0L) {
      stop(
        context, " names a group the study does not hold: ",
        paste(unknown, collapse = ", "),
        ". `$load_rawbatch()` reads one file per name in `group_names`, ",
        "which holds: ", paste(group_names, collapse = ", "),
        ". Add the group to `RegistryStudy$new(group_names = ...)`, or name ",
        "one that is already there.",
        call. = FALSE
      )
    }
  }
  new_cols <- .entry_columns(entry)
  for (i in seq_along(registry)) {
    clash <- intersect(new_cols, .entry_columns(registry[[i]]))
    if (length(clash) == 0L) {
      next
    }
    stop(
      context, " generates a column that ", .entry_context(registry[[i]]),
      " already generates: ", .format_col_list(clash),
      ". Every entry MUST own its output columns alone. ",
      "`$drop_code_entry()` removes exactly the columns an entry declares, ",
      "so a shared column disappears when either owner is dropped.",
      call. = FALSE
    )
  }
  return(invisible(TRUE))
}

# Apply ONE registry entry to a skeleton, and RETURN the skeleton.
#
# The return value is the contract. data.table cannot grow a column-pointer
# vector in place, so an entry that runs out of free column slots writes its
# columns to a NEW table and the caller keeps the old one. This function
# reserves the slots the entry needs before it runs, treats `skeleton` as a
# value it reassigns, and returns what it ends with. Every caller MUST assign
# that return value. `Skeleton$apply_code_entry()` does.
#
# This is the per-entry body extracted from apply_codes_to_skeleton() so the
# Skeleton R6 class can call it one entry at a time during incremental code
# registry sync. apply_codes_to_skeleton() itself becomes a thin loop around
# this helper for the "apply everything at once" path.
#
# Derived entries (kind = "derived") bypass batch_data entirely -- they
# OR together already-existing skeleton columns under new names. All
# source columns referenced by `reg$from` must already exist on the
# skeleton; they're produced by PRIMARY entries registered earlier in
# registration order. sync_with_registry() walks the registry in order,
# which keeps this invariant during incremental apply.
#
# ONE snapshot per entry, taken here, checked here. Not one per group: the
# snapshot copies the four structural columns, and that cost is per call.
#
# A group whose rawbatch slice holds zero rows still calls `fn`, with that
# zero-row table. `save_rawbatch()` writes a file for every group and every
# batch, and `payload_for_batch()` yields a zero-row slice when no person in
# the batch matches, so the columns are right and only the rows are absent.
# The entry's own no-match value therefore reaches the skeleton, rather than
# a `FALSE` this file invented.
#
# The column-naming logic here MUST match .entry_columns() above or the
# Skeleton's drop_code_entry() will leak orphan columns. The parity tests
# guard this invariant.
.apply_code_entry_impl <- function(skeleton, batch_data, reg, id_col) {
  # One growth, up front, for every branch. `.entry_columns()` predicts what
  # the entry writes, and the parity tests hold that prediction to what the
  # built-in functions do. `.DT_ALLOC_ENTRY_MARGIN` covers a scratch column
  # the prediction cannot see. The margin is a performance choice: a `fn`
  # that outgrows it still writes every column, and the growth it forces is
  # accepted because it keeps every column vector.
  skeleton <- .grow_dt_alloc(
    skeleton,
    sum(!.entry_columns(reg) %in% names(skeleton)) + .DT_ALLOC_ENTRY_MARGIN
  )
  pre <- skeleton_snapshot(skeleton)

  kind <- reg$kind %||% "primary"
  skeleton <- if (identical(kind, "derived")) {
    .apply_derived_entry_impl(skeleton, reg)
  } else {
    .apply_primary_entry_impl(skeleton, batch_data, reg, id_col)
  }

  validate_skeleton_after_add(
    skeleton,
    pre,
    context = .entry_context(reg),
    may_replace = .entry_columns(reg)
  )
  .assert_entry_columns_present(skeleton, reg)
  return(invisible(skeleton))
}

# The label the errors of one entry carry.
.entry_context <- function(reg) {
  if (identical(reg$kind %||% "primary", "derived")) {
    return(sprintf("$register_derived_codes(%s)", reg$label %||% "<anon>"))
  }
  return(sprintf("$register_codes(%s)", reg$label %||% "<anon>"))
}

# The primary branch: one call to `fn` per group, plus one for `combine_as`.
.apply_primary_entry_impl <- function(skeleton, batch_data, reg, id_col) {
  context <- .entry_context(reg)

  for (i in seq_along(reg$groups)) {
    group_names <- reg$groups[[i]]
    prefix <- names(reg$groups)[i]

    # Prefix code names
    if (!is.null(prefix) && nzchar(prefix)) {
      prefixed_codes <- stats::setNames(
        reg$codes,
        paste0(prefix, "_", names(reg$codes))
      )
    } else {
      prefixed_codes <- reg$codes
    }

    # Assigned, not passed as an expression. An argument is a promise, and
    # `fn` forces it only when it reads `dataset`. The absent-group check
    # below would then never run for a function that ignores its dataset.
    data <- .entry_group_data(batch_data, group_names, context)
    skeleton <- .call_entry_fn(
      skeleton,
      reg,
      data,
      id_col,
      prefixed_codes,
      context = context
    )
  }

  # Combined (combine_as)
  if (!is.null(reg$combine_as)) {
    combined_codes <- stats::setNames(
      reg$codes,
      paste0(reg$combine_as, "_", names(reg$codes))
    )
    combined_context <- sprintf(
      "$register_codes(%s, combine_as = %s)",
      reg$label %||% "<anon>",
      reg$combine_as
    )
    combined_data <- .entry_group_data(
      batch_data,
      unique(unlist(reg$groups)),
      combined_context
    )
    skeleton <- .call_entry_fn(
      skeleton,
      reg,
      combined_data,
      id_col,
      combined_codes,
      context = combined_context
    )
  }

  return(skeleton)
}

# The rawbatch table one group of one entry reads.
#
# An ABSENT group name is a configuration error, not an empty batch.
# `RegistryStudy$load_rawbatch()` stops on a missing file, so every name in
# `study$group_names` reaches this function with a table. A name that does
# not is a name the study never declared, and skipping it would record the
# entry as applied over data it never read.
#
# A group whose table holds zero rows is normal. It is what
# `payload_for_batch()` writes when no person in the batch has a record.
# Bind only the non-empty tables where there are any, which is what this
# function did before it handled the empty case, and bind the empty ones
# otherwise so `fn` still receives the right columns.
.entry_group_data <- function(batch_data, group_names, context) {
  # `list()[["g"]]` raises "subscript out of bounds" on a list with no
  # names, so test membership before indexing.
  present <- group_names %in% names(batch_data)
  absent <- group_names[!present]
  if (length(absent) > 0L) {
    stop(
      context, " names a rawbatch group that is not in this batch: ",
      paste(absent, collapse = ", "),
      ". Every group a registry entry reads MUST be in the study's ",
      "`group_names`, so `$load_rawbatch()` reads a file for it. A group ",
      "with no record for this batch arrives as a table with zero rows, ",
      "never as an absent name.",
      call. = FALSE
    )
  }
  tables <- lapply(group_names, function(g) batch_data[[g]])
  non_empty <- Filter(function(x) nrow(x) > 0L, tables)
  return(data.table::rbindlist(
    if (length(non_empty) > 0L) non_empty else tables,
    use.names = TRUE,
    fill = TRUE
  ))
}

# Every column `.entry_columns()` predicts MUST be on the skeleton once the
# entry has run. `Skeleton$apply_code_entry()` records the entry straight
# after this call, and `$drop_code_entry()` later removes exactly this set,
# so an absent column here becomes an entry that is recorded but not applied.
.assert_entry_columns_present <- function(skeleton, reg) {
  expected <- .entry_columns(reg)
  missing_cols <- setdiff(expected, names(skeleton))
  if (length(missing_cols) == 0L) {
    return(invisible(skeleton))
  }
  stop(
    .entry_context(reg),
    " finished without the columns it declares: ",
    .format_col_list(missing_cols),
    ". Every column `.entry_columns()` predicts must exist once the entry ",
    "has run, because the entry is recorded as applied straight afterwards. ",
    "A function that runs out of free column slots and returns NULL loses ",
    "its columns: return the skeleton instead.",
    call. = FALSE
  )
}

# Call one registry entry's `fn` and RETURN the skeleton it wrote to.
#
# `fn` writes to the skeleton by reference. Two things can still leave the
# result somewhere other than the table this function was handed:
#
#   * a REBIND of `skeleton` in this frame. `[.data.table` does this when it
#     grows a column-pointer vector, and `.ensure_dt_alloc()` does it inside
#     every built-in `add_*`. The call below passes the NAME `skeleton`, not
#     its value, so `substitute()` inside `fn` yields a name and the rebind
#     lands here.
#   * a RETURNED data.table.
#
# The frame binding always wins. A returned table is adopted ONLY when it is
# the same skeleton, which means it holds every column the skeleton held
# before, each at the same vector address. A grown table satisfies that: the
# growth builds a new header and keeps every vector.
#
# Any other returned table is IGNORED, which is what swereg did before
# 26.10.14. An `add_*` function often ends on a statement that returns
# something incidental. `dataset[, scratch := NULL]` returns `dataset`, and
# the batched pipeline permits that mutation. A returned table that carries
# the entry's columns but not the skeleton's vectors is ignored the same way,
# and the expected-column check below then reports what is missing.
#
# The expected-column check is cheap and reads names only. It names the
# group that failed, which the entry-level check cannot.
.call_entry_fn <- function(skeleton, reg, data, id_col, codes, context) {
  before <- .column_addresses(skeleton)

  # `quote(skeleton)` and `quote(data)` keep the NAMES in the call, and the
  # call is evaluated in this frame. `do.call()` with the values instead
  # would give `substitute(skeleton)` a data.table, which is not a binding,
  # so a built-in's rebind would have nowhere to land.
  cl <- as.call(c(
    list(reg$fn, quote(skeleton), quote(data)),
    list(id_name = id_col, codes = codes),
    reg$fn_args
  ))
  result <- eval(cl, envir = environment())

  if (data.table::is.data.table(result) && .is_same_table(result, before)) {
    skeleton <- result
  }

  if (!data.table::is.data.table(skeleton)) {
    stop(
      context, " broke reference semantics: the object it left behind is ",
      "no longer a data.table (got ",
      paste(class(skeleton), collapse = "/"), ").",
      call. = FALSE
    )
  }
  missing_cols <- setdiff(names(codes), names(skeleton))
  if (length(missing_cols) > 0L) {
    stop(
      context, " did not add the expected columns: ",
      .format_col_list(missing_cols),
      ". Check that your loop over `names(codes)` actually writes ",
      "to the skeleton (e.g. `skeleton[..., (nm) := TRUE]`). ",
      "A function that runs out of free column slots and returns a NEW ",
      "table loses its columns: write into the skeleton it was given.",
      call. = FALSE
    )
  }
  return(skeleton)
}

# Is `x` the table those column addresses came from, possibly grown?
#
# Every column the table held before MUST be present, and MUST still be the
# same vector. `setalloccol()` satisfies that: it builds a new header and
# keeps every vector. `copy()`, `merge()` and a `.()` projection do not.
#' @noRd
.is_same_table <- function(x, before) {
  now <- .column_addresses(x)
  kept <- names(before)
  if (!all(kept %in% names(now))) {
    return(FALSE)
  }
  return(all(vapply(
    kept,
    function(nm) identical(now[[nm]], before[[nm]]),
    logical(1)
  )))
}

# Apply one derived entry and RETURN the skeleton.
#
# Each `:=` here can grow the column-pointer vector, which rebinds this
# function's own local. The return value is what carries that growth out.
.apply_derived_entry_impl <- function(skeleton, reg) {
  for (nm in names(reg$codes)) {
    src_cols <- paste0(reg$from, "_", nm)
    missing_cols <- setdiff(src_cols, names(skeleton))
    if (length(missing_cols)) {
      stop(
        "register_derived_codes: source columns missing from skeleton: ",
        paste(missing_cols, collapse = ", "),
        ". Primary entries producing these columns must be registered ",
        "BEFORE the derived entry.",
        call. = FALSE
      )
    }
    out_col <- paste0(reg$as, "_", nm)
    skeleton[,
      (out_col) := Reduce("|", lapply(src_cols, function(c) get(c)))
    ]
  }
  return(skeleton)
}


# Per-column counts emitted by Skeleton$apply_code_entry() for every column
# a registry entry contributes to the skeleton. Stored on the entry's
# applied_registry record (under $counts) so the meta sidecar serialises
# them automatically and $compute_summary() can sum across batches without
# touching the heavy skeleton data files.
#
# Returns a named list keyed by column name; each value is a small list:
#   $n_persons_with       distinct ids where the column was TRUE in this batch
#   $n_person_weeks_with  rows where the column was TRUE in this batch
#
# Only logical columns get counts; non-logical columns (factor / numeric /
# character demographics added by randvars or framework) are silently
# skipped because $compute_summary() reports cohort presence, not value
# distributions -- those belong in $compute_population() or downstream
# Table 1 logic.
#
# `dt` is the skeleton data.table; the row-key column is hardcoded as "id"
# per the skeleton convention. (The study's `id_col` refers to the rawbatch
# join key, e.g. "lopnr" -- not the skeleton's own row-key.)
.compute_entry_column_counts <- function(dt, cols) {
  if (length(cols) == 0L) {
    return(list())
  }
  ids_all <- dt[["id"]]
  has_isoyear_flag <- "is_isoyear" %in% names(dt)
  is_weekly <- if (has_isoyear_flag) !dt$is_isoyear else rep(FALSE, nrow(dt))
  is_annual <- if (has_isoyear_flag) dt$is_isoyear else rep(FALSE, nrow(dt))

  out <- vector("list", length(cols))
  names(out) <- cols
  for (col in cols) {
    v <- dt[[col]]
    if (!is.logical(v)) {
      next
    }
    v_na <- !is.na(v) & v
    n_persons <- if (is.null(ids_all) || !any(v_na)) {
      0L
    } else {
      data.table::uniqueN(ids_all[v_na])
    }
    out[[col]] <- list(
      n_persons_with = as.integer(n_persons),
      n_person_weeks_with = as.integer(sum(v_na & is_weekly)),
      n_person_years_with = as.integer(sum(v_na & is_annual))
    )
  }
  return(out[!vapply(out, is.null, logical(1))])
}
