# =============================================================================
# S7 Classes for Target Trial Emulation
# =============================================================================
# Object-oriented design for TTE workflows using S7 classes.
# TTEDesign: Holds column name mappings - the "schema" for trial data
# TTETrial: Holds data + design + state, with methods for chaining operations
# =============================================================================

# Define nullable character type for optional properties
nullable_character <- S7::new_union(S7::class_character, NULL)

# -----------------------------------------------------------------------------
# TTEDesign: Trial design specification
# -----------------------------------------------------------------------------

#' TTEDesign class for target trial emulation
#'
#' Holds column name mappings that define the schema for trial data. This
#' allows specifying variable names once and reusing them across all TTE
#' workflow functions.
#'
#' @param person_id_var Character or NULL, name of the person identifier column
#'   for pre-panel (person-week) data. Required for [tte_match()] and
#'   [tte_expand()] operations. (default: NULL).
#' @param id_var Character, name of the trial identifier column. Auto-generated
#'   by [tte_expand()] as "trial_id" (default: "trial_id").
#' @param exposure_var Character, name of the baseline exposure/treatment column.
#' @param outcome_vars Character vector, names of outcome event indicator columns.
#' @param confounder_vars Character vector, names of confounder columns for
#'   propensity/censoring models.
#' @param follow_up_time Integer, expected follow-up duration in time units.
#' @param tstart_var Character, name of period start time column (default: "tstart").
#' @param tstop_var Character, name of period end time column (default: "tstop").
#' @param time_exposure_var Character or NULL, name of time-varying exposure column
#'   for per-protocol analysis (default: NULL).
#' @param eligible_var Character or NULL, name of eligibility indicator column
#'   (default: NULL).
#' @param admin_censor_var Character or NULL, name of administrative censoring
#'   boundary column (default: NULL). Mutually exclusive with
#'   `admin_censor_isoyearweek`.
#' @param admin_censor_isoyearweek Character or NULL, the study end date in
#'   ISO year-week format (e.g., "2023-52"). When set, administrative censoring
#'   is computed internally as weeks from each trial's entry date to this
#'   global study end date. Requires an `isoyearweek` column in the data.
#'   Mutually exclusive with `admin_censor_var` (default: NULL).
#'
#' @examples
#' # Design for post-panel (trial-level) data
#' design <- tte_design(
#'   id_var = "trial_id",
#'   exposure_var = "baseline_exposed",
#'   outcome_vars = c("death", "hosp"),
#'   confounder_vars = c("age", "education"),
#'   follow_up_time = 156L
#' )
#'
#' # Design for pre-panel (person-week) data with full workflow
#' design_prepanel <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "baseline_exposed",
#'   outcome_vars = c("death", "hosp"),
#'   confounder_vars = c("age", "education"),
#'   follow_up_time = 156L,
#'   eligible_var = "eligible"
#' )
#'
#' @family tte_classes
#' @seealso [tte_trial()] for creating trial objects, [TTETrial] for the trial class
#' @export
TTEDesign <- S7::new_class(
  "TTEDesign",
  properties = list(
    # Person identifier (for pre-panel data)
    person_id_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Trial identifier - defaults to "trial_id", auto-generated by tte_expand()
    id_var = S7::new_property(S7::class_character, default = "trial_id"),

    # Required exposure
    exposure_var = S7::class_character,

    # Outcomes (multiple possible)
    outcome_vars = S7::class_character,

    # Confounders for propensity/censoring models
    confounder_vars = S7::class_character,

    # Follow-up
    follow_up_time = S7::class_integer,

    # Time variables
    tstart_var = S7::new_property(S7::class_character, default = "tstart"),
    tstop_var = S7::new_property(S7::class_character, default = "tstop"),

    # Optional: time-varying exposure (for per-protocol)
    time_exposure_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Optional: eligibility column
    eligible_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Optional: administrative censoring boundary
    admin_censor_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Optional: administrative censoring boundary as isoyearweek (format: "YYYY-WW")
    # When set, admin censoring is computed internally as weeks from entry to this date
    admin_censor_isoyearweek = S7::new_property(
      nullable_character,
      default = NULL
    )
  ),
  validator = function(self) {
    if (length(self@person_id_var) > 0 && length(self@person_id_var) != 1) {
      return("person_id_var must be length 1 or NULL")
    }
    if (length(self@id_var) != 1) return("id_var must be length 1")
    if (length(self@exposure_var) != 1) return("exposure_var must be length 1")
    if (length(self@outcome_vars) == 0) return("outcome_vars cannot be empty")
    if (length(self@follow_up_time) != 1 || self@follow_up_time <= 0) {
      return("follow_up_time must be a positive integer")
    }
    if (length(self@tstart_var) != 1) return("tstart_var must be length 1")
    if (length(self@tstop_var) != 1) return("tstop_var must be length 1")
    if (length(self@time_exposure_var) > 0 && length(self@time_exposure_var) != 1) {
      return("time_exposure_var must be length 1 or NULL")
    }
    if (length(self@eligible_var) > 0 && length(self@eligible_var) != 1) {
      return("eligible_var must be length 1 or NULL")
    }
    if (length(self@admin_censor_var) > 0 && length(self@admin_censor_var) != 1) {
      return("admin_censor_var must be length 1 or NULL")
    }
    if (length(self@admin_censor_isoyearweek) > 0 &&
        length(self@admin_censor_isoyearweek) != 1) {
      return("admin_censor_isoyearweek must be length 1 or NULL")
    }
    # Mutual exclusivity check
    if (length(self@admin_censor_var) > 0 &&
        length(self@admin_censor_isoyearweek) > 0) {
      return("admin_censor_var and admin_censor_isoyearweek are mutually exclusive")
    }
    NULL
  }
)

#' Create a TTE design specification
#'
#' Constructor function for [TTEDesign] objects. Defines the column name
#' mappings for a target trial emulation analysis.
#'
#' @param exposure_var Character, name of the baseline exposure/treatment column.
#' @param outcome_vars Character vector, names of outcome event indicator columns.
#' @param confounder_vars Character vector, names of confounder columns.
#' @param follow_up_time Integer, expected follow-up duration in time units.
#' @param person_id_var Character or NULL, name of the person identifier column
#'   for pre-panel (person-week) data. Required for [tte_match()] and
#'   [tte_expand()] operations. (default: NULL).
#' @param id_var Character, name of the trial identifier column. Auto-generated
#'   by [tte_expand()] as "trial_id" (default: "trial_id").
#' @param tstart_var Character, period start time column (default: "tstart").
#' @param tstop_var Character, period end time column (default: "tstop").
#' @param time_exposure_var Character or NULL, time-varying exposure column
#'   for per-protocol analysis (default: NULL).
#' @param eligible_var Character or NULL, eligibility indicator column
#'   (default: NULL).
#' @param admin_censor_var Character or NULL, administrative censoring
#'   boundary column (default: NULL). Mutually exclusive with
#'   `admin_censor_isoyearweek`.
#' @param admin_censor_isoyearweek Character or NULL, the study end date in
#'   ISO year-week format (e.g., "2023-52"). When set, administrative censoring
#'   is computed internally by [tte_prepare_outcome()]. Mutually exclusive with
#'   `admin_censor_var` (default: NULL).
#'
#' @return A [TTEDesign] object.
#'
#' @examples
#' # Design for post-panel (trial-level) data
#' design <- tte_design(
#'   exposure_var = "baseline_exposed",
#'   time_exposure_var = "current_exposed",
#'   outcome_vars = c("death", "hospitalization"),
#'   confounder_vars = c("age", "sex", "education"),
#'   follow_up_time = 156L
#' )
#'
#' # Design for pre-panel (person-week) data
#' design_prepanel <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "baseline_exposed",
#'   outcome_vars = c("death", "hospitalization"),
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 156L,
#'   eligible_var = "eligible"
#' )
#'
#' @family tte_classes
#' @seealso [TTEDesign] for class details, [tte_trial()] for creating trials
#' @export
tte_design <- function(
    exposure_var,
    outcome_vars,
    confounder_vars,
    follow_up_time,
    person_id_var = NULL,
    id_var = "trial_id",
    tstart_var = "tstart",
    tstop_var = "tstop",
    time_exposure_var = NULL,
    eligible_var = NULL,
    admin_censor_var = NULL,
    admin_censor_isoyearweek = NULL
) {
  TTEDesign(
    person_id_var = person_id_var,
    id_var = id_var,
    exposure_var = exposure_var,
    outcome_vars = outcome_vars,
    confounder_vars = confounder_vars,
    follow_up_time = as.integer(follow_up_time),
    tstart_var = tstart_var,
    tstop_var = tstop_var,
    time_exposure_var = time_exposure_var,
    eligible_var = eligible_var,
    admin_censor_var = admin_censor_var,
    admin_censor_isoyearweek = admin_censor_isoyearweek
  )
}


# -----------------------------------------------------------------------------
# TTETrial: Trial data with design and state
# -----------------------------------------------------------------------------

#' TTETrial class for target trial emulation
#'
#' Holds the trial data, design specification, and workflow state. Methods
#' modify and return self for chaining operations in a fluent API.
#'
#' @param data A data.table containing the trial data.
#' @param design A [TTEDesign] object specifying column mappings.
#' @param data_level Character, either "person_week" for pre-panel data or
#'   "trial" for post-panel data. Determines which methods can be applied.
#' @param steps_completed Character vector of completed workflow steps.
#' @param active_outcome Character or NULL, the current outcome for IPCW-PP analysis.
#' @param weight_cols Character vector of weight column names created.
#'
#' @details
#' The `data_level` property controls which methods are available:
#' - `"person_week"`: Data has one row per person per time unit. Methods
#'   [tte_match()] and [tte_expand()] require this level.
#' - `"trial"`: Data has been expanded to trial panels. Methods [tte_collapse()],
#'   [tte_ipw()], [tte_prepare_outcome()], [tte_ipcw_pp()], [tte_weights()], and
#'   [tte_truncate()] require this level.
#'
#' The [tte_expand()] method transitions data from "person_week" to "trial" level.
#'
#' @examples
#' \dontrun{
#' # For trial-level data
#' design <- tte_design(
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L
#' )
#' trial <- tte_trial(my_trial_data, design)
#'
#' # For person-week data (full workflow)
#' design <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L,
#'   eligible_var = "eligible"
#' )
#' trial <- tte_trial(my_person_week_data, design) |>
#'   tte_match(ratio = 2) |>
#'   tte_expand()
#' }
#'
#' @family tte_classes
#' @seealso [tte_trial()] for creating trial objects, [TTEDesign] for design class
#' @export
TTETrial <- S7::new_class(
  "TTETrial",
  properties = list(
    data = S7::class_any,  # data.table
    design = TTEDesign,

    # Data level: "person_week" or "trial"
    data_level = S7::new_property(
      S7::class_character,
      default = "trial"
    ),

    # State tracking
    steps_completed = S7::new_property(
      S7::class_character,
      default = character()
    ),

    # Active outcome for per-protocol analysis
    # (IPCW-PP is outcome-specific because event censors follow-up)
    active_outcome = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Weight columns created
    weight_cols = S7::new_property(
      S7::class_character,
      default = character()
    )
  ),
  validator = function(self) {
    if (!data.table::is.data.table(self@data)) {
      return("data must be a data.table")
    }

    # Validate data_level
    if (!self@data_level %in% c("person_week", "trial")) {
      return("data_level must be 'person_week' or 'trial'")
    }

    # Validate based on data_level
    if (self@data_level == "person_week") {
      # Requires person_id_var
      if (length(self@design@person_id_var) == 0) {
        return("person_week data requires person_id_var in design")
      }
      if (!self@design@person_id_var %in% names(self@data)) {
        return(paste(
          "person_week data requires person_id_var column:",
          self@design@person_id_var
        ))
      }
    } else {
      # Requires id_var (trial_id)
      if (!self@design@id_var %in% names(self@data)) {
        return(paste(
          "trial data requires id_var column:",
          self@design@id_var
        ))
      }
    }

    # Validate exposure_var exists
    if (!self@design@exposure_var %in% names(self@data)) {
      return(paste(
        "Missing required column:",
        self@design@exposure_var
      ))
    }

    # Validate active_outcome is in design (if set)
    # Note: S7 nullable character defaults to character(0), not NULL
    if (length(self@active_outcome) > 0 &&
        !self@active_outcome %in% self@design@outcome_vars) {
      return("active_outcome must be one of design@outcome_vars")
    }
    NULL
  }
)

#' Create a TTE trial object
#'
#' Constructor function for [TTETrial] objects. Wraps trial data with a design
#' specification to enable fluent method chaining.
#'
#' @param data A data.table containing the trial data.
#' @param design A [TTEDesign] object specifying column mappings.
#' @param data_level Character or NULL. If NULL (default), auto-detects based on
#'   which identifier column exists in data. "person_week" for pre-panel data
#'   (requires person_id_var), "trial" for post-panel data (requires id_var).
#'
#' @return A [TTETrial] object.
#'
#' @examples
#' \dontrun{
#' # Trial-level data (auto-detected)
#' design <- tte_design(
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L
#' )
#' trial <- tte_trial(my_trial_data, design) |>
#'   tte_collapse(period_width = 4) |>
#'   tte_ipw()
#'
#' # Person-week data (auto-detected, full workflow)
#' design <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L,
#'   eligible_var = "eligible"
#' )
#' trial <- tte_trial(my_person_week_data, design) |>
#'   tte_match(ratio = 2) |>
#'   tte_expand() |>
#'   tte_collapse(period_width = 4) |>
#'   tte_ipw()
#' }
#'
#' @family tte_classes
#' @seealso [TTETrial] for class details, [tte_design()] for creating designs
#' @export
tte_trial <- function(data, design, data_level = NULL) {
  # Make a copy to avoid modifying original
  if (!data.table::is.data.table(data)) {
    data <- data.table::as.data.table(data)
  } else {
    data <- data.table::copy(data)
  }

  # Auto-detect data_level if not specified
  if (is.null(data_level)) {
    has_trial_id <- design@id_var %in% names(data)
    has_person_id <- length(design@person_id_var) > 0 &&
      design@person_id_var %in% names(data)

    if (has_trial_id && !has_person_id) {
      data_level <- "trial"
    } else if (has_person_id && !has_trial_id) {
      data_level <- "person_week"
    } else if (has_trial_id && has_person_id) {
      # Both present - default to trial level (post-panel data usually has both)
      data_level <- "trial"
    } else {
      stop(
        "Cannot auto-detect data_level. Data must have either:\n",
        "  - person_id_var ('", design@person_id_var, "') for person_week data, or\n",
        "  - id_var ('", design@id_var, "') for trial data"
      )
    }
  }

  TTETrial(
    data = data,
    design = design,
    data_level = data_level
  )
}
