# =============================================================================
# S7 Classes for Target Trial Emulation
# =============================================================================
# Object-oriented design for TTE workflows using S7 classes.
# TTEDesign: Holds column name mappings - the "schema" for trial data
# TTETrial: Holds data + design + state, with methods for chaining operations
# =============================================================================

# Define nullable character type for optional properties
nullable_character <- S7::new_union(S7::class_character, NULL)

# -----------------------------------------------------------------------------
# TTEDesign: Trial design specification
# -----------------------------------------------------------------------------

#' TTEDesign class for target trial emulation
#'
#' Holds column name mappings that define the schema for trial data. This
#' allows specifying variable names once and reusing them across all TTE
#' workflow functions.
#'
#' @param person_id_var Character or NULL, name of the person identifier column
#'   for pre-panel (person-week) data. Required for [tte_match()] and
#'   [tte_expand()] operations. (default: NULL).
#' @param id_var Character, name of the trial identifier column. Auto-generated
#'   by [tte_expand()] as "trial_id" (default: "trial_id").
#' @param exposure_var Character, name of the baseline exposure/treatment column.
#' @param outcome_vars Character vector, names of outcome event indicator columns.
#' @param confounder_vars Character vector, names of confounder columns for
#'   propensity/censoring models.
#' @param follow_up_time Integer, expected follow-up duration in time units.
#' @param tstart_var Character, name of period start time column (default: "tstart").
#' @param tstop_var Character, name of period end time column (default: "tstop").
#' @param time_exposure_var Character or NULL, name of time-varying exposure column
#'   for per-protocol analysis (default: NULL).
#' @param eligible_var Character or NULL, name of eligibility indicator column
#'   (default: NULL).
#' @param admin_censor_var Character or NULL, name of administrative censoring
#'   boundary column (default: NULL). Mutually exclusive with
#'   `admin_censor_isoyearweek`.
#' @param admin_censor_isoyearweek Character or NULL, the study end date in
#'   ISO year-week format (e.g., "2023-52"). When set, administrative censoring
#'   is computed internally as weeks from each trial's entry date to this
#'   global study end date. Requires an `isoyearweek` column in the data.
#'   Mutually exclusive with `admin_censor_var` (default: NULL).
#'
#' @examples
#' # Design for post-panel (trial-level) data
#' design <- tte_design(
#'   id_var = "trial_id",
#'   exposure_var = "baseline_exposed",
#'   outcome_vars = c("death", "hosp"),
#'   confounder_vars = c("age", "education"),
#'   follow_up_time = 156L
#' )
#'
#' # Design for pre-panel (person-week) data with full workflow
#' design_prepanel <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "baseline_exposed",
#'   outcome_vars = c("death", "hosp"),
#'   confounder_vars = c("age", "education"),
#'   follow_up_time = 156L,
#'   eligible_var = "eligible"
#' )
#'
#' @family tte_classes
#' @seealso [tte_trial()] for creating trial objects, [TTETrial] for the trial class
#' @export
TTEDesign <- S7::new_class(
  "TTEDesign",
  properties = list(
    # Person identifier (for pre-panel data)
    person_id_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Trial identifier - defaults to "trial_id", auto-generated by tte_expand()
    id_var = S7::new_property(S7::class_character, default = "trial_id"),

    # Required exposure
    exposure_var = S7::class_character,

    # Outcomes (multiple possible)
    outcome_vars = S7::class_character,

    # Confounders for propensity/censoring models
    confounder_vars = S7::class_character,

    # Follow-up
    follow_up_time = S7::class_integer,

    # Time variables
    tstart_var = S7::new_property(S7::class_character, default = "tstart"),
    tstop_var = S7::new_property(S7::class_character, default = "tstop"),

    # Optional: time-varying exposure (for per-protocol)
    time_exposure_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Optional: eligibility column
    eligible_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Optional: administrative censoring boundary
    admin_censor_var = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Optional: administrative censoring boundary as isoyearweek (format: "YYYY-WW")
    # When set, admin censoring is computed internally as weeks from entry to this date
    admin_censor_isoyearweek = S7::new_property(
      nullable_character,
      default = NULL
    )
  ),
  validator = function(self) {
    if (length(self@person_id_var) > 0 && length(self@person_id_var) != 1) {
      return("person_id_var must be length 1 or NULL")
    }
    if (length(self@id_var) != 1) return("id_var must be length 1")
    if (length(self@exposure_var) != 1) return("exposure_var must be length 1")
    if (length(self@outcome_vars) == 0) return("outcome_vars cannot be empty")
    if (length(self@follow_up_time) != 1 || self@follow_up_time <= 0) {
      return("follow_up_time must be a positive integer")
    }
    if (length(self@tstart_var) != 1) return("tstart_var must be length 1")
    if (length(self@tstop_var) != 1) return("tstop_var must be length 1")
    if (length(self@time_exposure_var) > 0 && length(self@time_exposure_var) != 1) {
      return("time_exposure_var must be length 1 or NULL")
    }
    if (length(self@eligible_var) > 0 && length(self@eligible_var) != 1) {
      return("eligible_var must be length 1 or NULL")
    }
    if (length(self@admin_censor_var) > 0 && length(self@admin_censor_var) != 1) {
      return("admin_censor_var must be length 1 or NULL")
    }
    if (length(self@admin_censor_isoyearweek) > 0 &&
        length(self@admin_censor_isoyearweek) != 1) {
      return("admin_censor_isoyearweek must be length 1 or NULL")
    }
    # Mutual exclusivity check
    if (length(self@admin_censor_var) > 0 &&
        length(self@admin_censor_isoyearweek) > 0) {
      return("admin_censor_var and admin_censor_isoyearweek are mutually exclusive")
    }
    NULL
  }
)

#' Create a TTE design specification
#'
#' Constructor function for [TTEDesign] objects. Defines the column name
#' mappings for a target trial emulation analysis.
#'
#' @param exposure_var Character, name of the baseline exposure/treatment column.
#' @param outcome_vars Character vector, names of outcome event indicator columns.
#' @param confounder_vars Character vector, names of confounder columns.
#' @param follow_up_time Integer, expected follow-up duration in time units.
#' @param person_id_var Character or NULL, name of the person identifier column
#'   for pre-panel (person-week) data. Required for [tte_match()] and
#'   [tte_expand()] operations. (default: NULL).
#' @param id_var Character, name of the trial identifier column. Auto-generated
#'   by [tte_expand()] as "trial_id" (default: "trial_id").
#' @param tstart_var Character, period start time column (default: "tstart").
#' @param tstop_var Character, period end time column (default: "tstop").
#' @param time_exposure_var Character or NULL, time-varying exposure column
#'   for per-protocol analysis (default: NULL).
#' @param eligible_var Character or NULL, eligibility indicator column
#'   (default: NULL).
#' @param admin_censor_var Character or NULL, administrative censoring
#'   boundary column (default: NULL). Mutually exclusive with
#'   `admin_censor_isoyearweek`.
#' @param admin_censor_isoyearweek Character or NULL, the study end date in
#'   ISO year-week format (e.g., "2023-52"). When set, administrative censoring
#'   is computed internally by [tte_prepare_outcome()]. Mutually exclusive with
#'   `admin_censor_var` (default: NULL).
#'
#' @return A [TTEDesign] object.
#'
#' @examples
#' # Design for post-panel (trial-level) data
#' design <- tte_design(
#'   exposure_var = "baseline_exposed",
#'   time_exposure_var = "current_exposed",
#'   outcome_vars = c("death", "hospitalization"),
#'   confounder_vars = c("age", "sex", "education"),
#'   follow_up_time = 156L
#' )
#'
#' # Design for pre-panel (person-week) data
#' design_prepanel <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "baseline_exposed",
#'   outcome_vars = c("death", "hospitalization"),
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 156L,
#'   eligible_var = "eligible"
#' )
#'
#' @family tte_classes
#' @seealso [TTEDesign] for class details, [tte_trial()] for creating trials
#' @export
tte_design <- function(
    exposure_var,
    outcome_vars,
    confounder_vars,
    follow_up_time,
    person_id_var = NULL,
    id_var = "trial_id",
    tstart_var = "tstart",
    tstop_var = "tstop",
    time_exposure_var = NULL,
    eligible_var = NULL,
    admin_censor_var = NULL,
    admin_censor_isoyearweek = NULL
) {
  TTEDesign(
    person_id_var = person_id_var,
    id_var = id_var,
    exposure_var = exposure_var,
    outcome_vars = outcome_vars,
    confounder_vars = confounder_vars,
    follow_up_time = as.integer(follow_up_time),
    tstart_var = tstart_var,
    tstop_var = tstop_var,
    time_exposure_var = time_exposure_var,
    eligible_var = eligible_var,
    admin_censor_var = admin_censor_var,
    admin_censor_isoyearweek = admin_censor_isoyearweek
  )
}


# -----------------------------------------------------------------------------
# TTETrial: Trial data with design and state
# -----------------------------------------------------------------------------

#' TTETrial class for target trial emulation
#'
#' Holds the trial data, design specification, and workflow state. Methods
#' modify and return self for chaining operations in a fluent API.
#'
#' @param data A data.table containing the trial data.
#' @param design A [TTEDesign] object specifying column mappings.
#' @param data_level Character, either "person_week" for pre-panel data or
#'   "trial" for post-panel data. Determines which methods can be applied.
#' @param steps_completed Character vector of completed workflow steps.
#' @param active_outcome Character or NULL, the current outcome for IPCW-PP analysis.
#' @param weight_cols Character vector of weight column names created.
#'
#' @details
#' The `data_level` property controls which methods are available:
#' - `"person_week"`: Data has one row per person per time unit. Methods
#'   [tte_match()] and [tte_expand()] require this level.
#' - `"trial"`: Data has been expanded to trial panels. Methods [tte_collapse()],
#'   [tte_ipw()], [tte_prepare_outcome()], [tte_ipcw_pp()], [tte_weights()], and
#'   [tte_truncate()] require this level.
#'
#' The [tte_expand()] method transitions data from "person_week" to "trial" level.
#'
#' @examples
#' \dontrun{
#' # For trial-level data
#' design <- tte_design(
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L
#' )
#' trial <- tte_trial(my_trial_data, design)
#'
#' # For person-week data (full workflow)
#' design <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L,
#'   eligible_var = "eligible"
#' )
#' trial <- tte_trial(my_person_week_data, design) |>
#'   tte_match(ratio = 2) |>
#'   tte_expand()
#' }
#'
#' @family tte_classes
#' @seealso [tte_trial()] for creating trial objects, [TTEDesign] for design class
#' @export
TTETrial <- S7::new_class(
  "TTETrial",
  properties = list(
    data = S7::class_any,  # data.table
    design = TTEDesign,

    # Data level: "person_week" or "trial"
    data_level = S7::new_property(
      S7::class_character,
      default = "trial"
    ),

    # State tracking
    steps_completed = S7::new_property(
      S7::class_character,
      default = character()
    ),

    # Active outcome for per-protocol analysis
    # (IPCW-PP is outcome-specific because event censors follow-up)
    active_outcome = S7::new_property(
      nullable_character,
      default = NULL
    ),

    # Weight columns created
    weight_cols = S7::new_property(
      S7::class_character,
      default = character()
    )
  ),
  validator = function(self) {
    if (!data.table::is.data.table(self@data)) {
      return("data must be a data.table")
    }

    # Validate data_level
    if (!self@data_level %in% c("person_week", "trial")) {
      return("data_level must be 'person_week' or 'trial'")
    }

    # Validate based on data_level
    if (self@data_level == "person_week") {
      # Requires person_id_var
      if (length(self@design@person_id_var) == 0) {
        return("person_week data requires person_id_var in design")
      }
      if (!self@design@person_id_var %in% names(self@data)) {
        return(paste(
          "person_week data requires person_id_var column:",
          self@design@person_id_var
        ))
      }
    } else {
      # Requires id_var (trial_id)
      if (!self@design@id_var %in% names(self@data)) {
        return(paste(
          "trial data requires id_var column:",
          self@design@id_var
        ))
      }
    }

    # Validate exposure_var exists
    if (!self@design@exposure_var %in% names(self@data)) {
      return(paste(
        "Missing required column:",
        self@design@exposure_var
      ))
    }

    # Validate active_outcome is in design (if set)
    # Note: S7 nullable character defaults to character(0), not NULL
    if (length(self@active_outcome) > 0 &&
        !self@active_outcome %in% self@design@outcome_vars) {
      return("active_outcome must be one of design@outcome_vars")
    }
    NULL
  }
)

#' Create a TTE trial object
#'
#' Constructor function for [TTETrial] objects. Wraps trial data with a design
#' specification to enable fluent method chaining.
#'
#' @param data A data.table containing the trial data.
#' @param design A [TTEDesign] object specifying column mappings.
#' @param data_level Character or NULL. If NULL (default), auto-detects based on
#'   which identifier column exists in data. "person_week" for pre-panel data
#'   (requires person_id_var), "trial" for post-panel data (requires id_var).
#'
#' @return A [TTETrial] object.
#'
#' @examples
#' \dontrun{
#' # Trial-level data (auto-detected)
#' design <- tte_design(
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L
#' )
#' trial <- tte_trial(my_trial_data, design) |>
#'   tte_collapse(period_width = 4) |>
#'   tte_ipw()
#'
#' # Person-week data (auto-detected, full workflow)
#' design <- tte_design(
#'   person_id_var = "id",
#'   exposure_var = "exposed",
#'   outcome_vars = "death",
#'   confounder_vars = c("age", "sex"),
#'   follow_up_time = 52L,
#'   eligible_var = "eligible"
#' )
#' trial <- tte_trial(my_person_week_data, design) |>
#'   tte_match(ratio = 2) |>
#'   tte_expand() |>
#'   tte_collapse(period_width = 4) |>
#'   tte_ipw()
#' }
#'
#' @family tte_classes
#' @seealso [TTETrial] for class details, [tte_design()] for creating designs
#' @export
tte_trial <- function(data, design, data_level = NULL) {
  # Make a copy to avoid modifying original
  if (!data.table::is.data.table(data)) {
    data <- data.table::as.data.table(data)
  } else {
    data <- data.table::copy(data)
  }

  # Auto-detect data_level if not specified
  if (is.null(data_level)) {
    has_trial_id <- design@id_var %in% names(data)
    has_person_id <- length(design@person_id_var) > 0 &&
      design@person_id_var %in% names(data)

    if (has_trial_id && !has_person_id) {
      data_level <- "trial"
    } else if (has_person_id && !has_trial_id) {
      data_level <- "person_week"
    } else if (has_trial_id && has_person_id) {
      # Both present - default to trial level (post-panel data usually has both)
      data_level <- "trial"
    } else {
      stop(
        "Cannot auto-detect data_level. Data must have either:\n",
        "  - person_id_var ('", design@person_id_var, "') for person_week data, or\n",
        "  - id_var ('", design@id_var, "') for trial data"
      )
    }
  }

  TTETrial(
    data = data,
    design = design,
    data_level = data_level
  )
}


# -----------------------------------------------------------------------------
# TTEPlan: Bundle of trial generation parameters
# -----------------------------------------------------------------------------

#' TTEPlan class for trial generation planning
#'
#' Bundles the ETT grid, skeleton file paths, and design column names into a
#' single object using a builder pattern. Create an empty plan with
#' [tte_plan()], then add ETTs one at a time with [tte_plan_add_one_ett()].
#' Supports `plan[[i]]` to extract the i-th task (enrollment) for
#' interactive testing.
#'
#' Design parameters (confounder_vars, person_id_var, exposure_var, etc.) are
#' stored per-ETT in the `ett` data.table, allowing different ETTs to use
#' different confounders or design columns. Within an enrollment_id (same
#' follow_up + age_group), design params must match.
#'
#' @param project_prefix Character, string used for file naming.
#' @param ett NULL or a data.table with per-ETT columns including design params.
#' @param skeleton_files Character vector of skeleton file paths.
#' @param global_max_isoyearweek Administrative censoring boundary (isoyearweek string).
#'
#' @examples
#' \dontrun{
#' plan <- tte_plan(
#'   project_prefix = "project002",
#'   skeleton_files = skeleton_files,
#'   global_max_isoyearweek = "2023-52"
#' )
#' plan <- plan |> tte_plan_add_one_ett(
#'   outcome_var = "death",
#'   outcome_name = "Death",
#'   follow_up = 52,
#'   age_group = "50_60",
#'   age_min = 50,
#'   age_max = 60,
#'   confounder_vars = c("age", "education"),
#'   time_exposure_var = "rd_exposed",
#'   eligible_var = "eligible"
#' )
#'
#' # Extract first task for interactive testing
#' task <- plan[[1]]
#' task$design
#' task$age_range
#' }
#'
#' @family tte_classes
#' @seealso [tte_plan()] for the constructor, [tte_plan_add_one_ett()] to add ETTs,
#'   [tte_plan_task()] to extract tasks, [tte_generate_enrollments()] for the pipeline
#' @export
TTEPlan <- S7::new_class(
  "TTEPlan",
  properties = list(
    project_prefix = S7::class_character,
    ett = S7::class_any,  # NULL or data.table
    skeleton_files = S7::class_character,
    global_max_isoyearweek = S7::class_any
  ),
  validator = function(self) {
    if (length(self@project_prefix) != 1) return("project_prefix must be length 1")
    if (length(self@skeleton_files) == 0) return("skeleton_files cannot be empty")
    if (!is.null(self@ett)) {
      if (!data.table::is.data.table(self@ett)) {
        return("ett must be a data.table or NULL")
      }
      if (nrow(self@ett) > 0) {
        required_cols <- c(
          "enrollment_id", "outcome_var", "follow_up", "age_min", "age_max",
          "confounder_vars", "person_id_var", "exposure_var"
        )
        missing <- setdiff(required_cols, names(self@ett))
        if (length(missing) > 0) {
          return(paste(
            "ett missing required columns:", paste(missing, collapse = ", ")
          ))
        }
      }
    }
    NULL
  }
)

#' Create an empty TTE plan
#'
#' Constructor for [TTEPlan] objects. Creates an empty plan with just
#' infrastructure parameters. Use [tte_plan_add_one_ett()] to add ETTs.
#'
#' @param project_prefix string used for file naming (e.g., "project002_ozel_psychosis").
#' @param skeleton_files Character vector of skeleton file paths.
#' @param global_max_isoyearweek Administrative censoring boundary (isoyearweek string).
#'
#' @return A [TTEPlan] object with no ETTs.
#'
#' @examples
#' \dontrun{
#' plan <- tte_plan(
#'   project_prefix = "project002",
#'   skeleton_files = skeleton_files,
#'   global_max_isoyearweek = "2023-52"
#' )
#' plan <- plan |> tte_plan_add_one_ett(
#'   outcome_var = "death",
#'   outcome_name = "Death",
#'   follow_up = 52,
#'   age_group = "50_60",
#'   age_min = 50,
#'   age_max = 60,
#'   confounder_vars = c("age", "sex", "education")
#' )
#' }
#'
#' @family tte_classes
#' @seealso [TTEPlan] for class details, [tte_plan_add_one_ett()] to add ETTs,
#'   [tte_generate_enrollments()] for the pipeline
#' @export
tte_plan <- function(project_prefix, skeleton_files, global_max_isoyearweek) {
  TTEPlan(
    project_prefix = project_prefix,
    skeleton_files = skeleton_files,
    global_max_isoyearweek = global_max_isoyearweek,
    ett = NULL
  )
}


#' Add one ETT to a TTE plan
#'
#' Adds exactly one Emulated Target Trial (ETT) row to a [TTEPlan] object.
#' Each ETT represents one outcome x follow_up x age_group combination with
#' its own design parameters (confounders, exposure columns, etc.).
#'
#' ETTs with the same `enrollment_id` share trial panels and must have matching
#' design parameters (person_id_var, exposure_var, time_exposure_var,
#' eligible_var, confounder_vars).
#'
#' @param plan A [TTEPlan] object.
#' @param enrollment_id Character, enrollment group identifier (e.g., "01").
#'   ETTs with the same enrollment_id share trial panels and must have matching
#'   design parameters.
#' @param outcome_var Character, name of the outcome column.
#' @param outcome_name Character, human-readable outcome name.
#' @param follow_up Integer, follow-up duration in weeks.
#' @param confounder_vars Character vector of confounder column names.
#' @param time_exposure_var Character or NULL, name of time-varying exposure
#'   column. NULL if ITT only. No default — must be explicit.
#' @param eligible_var Character or NULL, name of eligibility column.
#'   NULL if no eligibility filter. No default — must be explicit.
#' @param argset Named list of additional parameters:
#'   \describe{
#'     \item{age_group}{Character, age group label (e.g., "50_60"). Required.}
#'     \item{age_min}{Numeric, minimum age. Required.}
#'     \item{age_max}{Numeric, maximum age. Required.}
#'     \item{person_id_var}{Character, name of person ID column. Default: "id".}
#'   }
#'
#' @return The modified [TTEPlan] object with one additional ETT row.
#'
#' @examples
#' \dontrun{
#' plan <- tte_plan("project002", skeleton_files, "2023-52")
#' argset <- list(age_group = "50_60", age_min = 50, age_max = 60)
#' plan <- plan |>
#'   tte_plan_add_one_ett(
#'     enrollment_id = "01",
#'     outcome_var = "death",
#'     outcome_name = "Death",
#'     follow_up = 52,
#'     confounder_vars = c("age", "education"),
#'     time_exposure_var = "rd_exposed",
#'     eligible_var = "eligible",
#'     argset = argset
#'   ) |>
#'   tte_plan_add_one_ett(
#'     enrollment_id = "01",
#'     outcome_var = "hosp",
#'     outcome_name = "Hospitalization",
#'     follow_up = 52,
#'     confounder_vars = c("age", "education"),
#'     time_exposure_var = "rd_exposed",
#'     eligible_var = "eligible",
#'     argset = argset
#'   )
#' }
#'
#' @family tte_classes
#' @seealso [tte_plan()] for creating an empty plan, [TTEPlan] for class details
#' @export
tte_plan_add_one_ett <- function(
    plan,
    enrollment_id,
    outcome_var,
    outcome_name,
    follow_up,
    confounder_vars,
    time_exposure_var,
    eligible_var,
    argset = list()
) {
  # Extract from argset
  age_group <- argset$age_group
  age_min <- argset$age_min
  age_max <- argset$age_max
  if (is.null(age_group) || is.null(age_min) || is.null(age_max)) {
    stop("argset must contain 'age_group', 'age_min', and 'age_max'")
  }
  person_id_var <- if (!is.null(argset$person_id_var)) argset$person_id_var else "id"
  exposure_var <- "baseline_exposed"

  # Convert NULL -> NA for data.table storage
  tv_exp <- if (is.null(time_exposure_var)) NA_character_ else time_exposure_var
  elig <- if (is.null(eligible_var)) NA_character_ else eligible_var

  # Validate: if this enrollment_id already exists, design params must match
  if (!is.null(plan@ett) && nrow(plan@ett) > 0) {
    rows_match <- plan@ett$enrollment_id == enrollment_id
    existing <- plan@ett[rows_match]
    if (nrow(existing) > 0) {
      first <- existing[1]
      if (first$person_id_var != person_id_var) {
        stop("person_id_var mismatch within enrollment_id ", enrollment_id)
      }
      if (first$exposure_var != exposure_var) {
        stop("exposure_var mismatch within enrollment_id ", enrollment_id)
      }
      first_tv <- first$time_exposure_var
      if (!identical(is.na(first_tv), is.na(tv_exp)) ||
          (!is.na(first_tv) && first_tv != tv_exp)) {
        stop("time_exposure_var mismatch within enrollment_id ", enrollment_id)
      }
      first_el <- first$eligible_var
      if (!identical(is.na(first_el), is.na(elig)) ||
          (!is.na(first_el) && first_el != elig)) {
        stop("eligible_var mismatch within enrollment_id ", enrollment_id)
      }
      if (!identical(first$confounder_vars[[1]], confounder_vars)) {
        stop("confounder_vars mismatch within enrollment_id ", enrollment_id)
      }
    }
  }

  # Compute ett_id, description, file names
  ett_num <- if (is.null(plan@ett)) 1L else nrow(plan@ett) + 1L
  ett_id <- paste0("ETT", sprintf("%02d", ett_num))
  description <- paste0(
    ett_id, ": ", outcome_name,
    " (", follow_up, "w, age ",
    stringr::str_replace(age_group, "_", "-"), ")"
  )
  prefix <- plan@project_prefix
  file_raw <- paste0(prefix, "_raw_", enrollment_id, ".qs")
  file_imp <- paste0(prefix, "_imp_", enrollment_id, ".qs")
  file_analysis <- paste0(prefix, "_analysis_", ett_id, ".qs")

  new_row <- data.table::data.table(
    enrollment_id = enrollment_id,
    ett_id = ett_id,
    age_group = age_group,
    age_min = age_min,
    age_max = age_max,
    follow_up = follow_up,
    outcome_var = outcome_var,
    outcome_name = outcome_name,
    description = description,
    file_raw = file_raw,
    file_imp = file_imp,
    file_analysis = file_analysis,
    confounder_vars = list(confounder_vars),
    person_id_var = person_id_var,
    exposure_var = exposure_var,
    time_exposure_var = tv_exp,
    eligible_var = elig
  )

  if (is.null(plan@ett)) {
    plan@ett <- new_row
  } else {
    plan@ett <- data.table::rbindlist(list(plan@ett, new_row), use.names = TRUE)
  }
  plan
}
